DOC Move docs to docs site
silverstripe/silverstripe-webauthn-authenticator pull request #174
Opened 2024-04-08 07:45 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-mfa/issues/531

2024-04-08 22:02 UTC, GuySartorelli requested changes
Why are you deleting a bunch of docs here? This should be renamed to the `docs/en/index.md` and pulled in from here.

2024-04-09 02:11 UTC, emteknetnz commented
Have moved to /docs/en and linked to from readme

2024-04-09 03:19 UTC, GuySartorelli requested changes

2024-04-09 03:19 UTC, GuySartorelli commented on docs/en/index.md
Please add title metadata as per all the other PRs.

2024-04-09 04:09 UTC, emteknetnz commented on docs/en/index.md
Sorry forgot to push

2024-04-09 04:39 UTC, GuySartorelli approved these changes
LGTM

2024-04-09 04:39 UTC, merged